<a href="https://colab.research.google.com/github/AlvinMathew001/AI-ML-Internship/blob/main/day4_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
df=pd.read_csv("/content/nlp_dataset.csv")
print(df)

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

stop_words=set(stopwords.words('english'))
print(stop_words)
lemmatizer=WordNetLemmatizer()
def process_text(text):
  word_tokens=word_tokenize(text)
  filtered_tokens=[word for word in word_tokens if word.lower() not in stop_words]
  lemmatized_tokens=[lemmatizer.lemmatize(word.lower()) for word in filtered_tokens]

  return{
      "Original_text":text,
      "Word_tokens":word_tokens,
      "Filtered_tokens":filtered_tokens,
      "Lemmatized_tokens":lemmatized_tokens
  }

  results= df['Text'],apply(process_text)
  processed_df=pd.DataFrame(results.tolist())
  print(processed_df.head())

  processed_file_path="processed_nlp_dataset.csv"
  processed_df.to_csv(process_file_path,index=False)

                                                Text
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...
5  Continuous research and innovation are improvi...
6  The potential of NLP is vast, making it essent...
{"didn't", 'hasn', 'isn', 'these', "they've", 'for', 'before', 'you', "won't", 'has', 'itself', 'ma', "they'd", 'until', "you'll", 'am', 'some', 'while', 'be', 'd', "mightn't", 'from', 'so', 'weren', 'only', 'they', 'your', "he'll", 'just', 't', 'very', 'with', "you'd", 'shouldn', 'in', 'our', "aren't", 'i', "hadn't", 'but', 'couldn', 'haven', "hasn't", 'who', 'when', "i'm", 'doing', 'each', 'm', "i'll", 'doesn', 'ours', 'he', "weren't", 'into', "haven't", 'during', 'yourself', "shouldn't", "they're", 'or', 'wouldn', 'them', 'to', 'was', "she'll", "they'll", "we're", 'it', 'their', 'no', 'of', 'at', 'any', 'and', "isn't", "we'd", 'shan', 'y', 'my', 'hadn', "we've", 'me', 've', 'where', 'its', 'how', 'yourselves', 'should', 'her', "you've", 'above', 'than', 'this', "we'll", "wasn't", 'all', 'out', "needn't", 'o', 'further', 'did', 'a', 'because', 'few', "that'll", "doesn't", 'll', "should've", "he'd", 'not', 'needn', 'do', 'most', 'have', 'why', 'were', 'aren', 'through', 'below', 'are', 'the', 'about', 'themselves', 'wasn', 's', 'him', 'then', 'won', 'whom', 'that', 'as', 'having', "i'd", "it'll", 'too', 'against', 'ain', 'himself', "couldn't", 'herself', 'we', 'hers', 'other', 'by', "wouldn't", "it'd", 'on', 'once', 'theirs', 'such', 'off', "don't", 'under', 'an', 'after', "she's", 'both', 'between', 'can', 'if', 'nor', 'there', 're', 'myself', 'those', "you're", 'she', "mustn't", 'didn', 'don', 'is', 'had', 'here', 'own', "she'd", 'his', 'more', 'down', 'up', 'been', 'mustn', "he's", 'again', "it's", 'same', "shan't", "i've", 'over', 'what', 'which', 'yours', 'will', 'mightn', 'now', 'does', 'being', 'ourselves'}

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [3]:
df

                                                Text
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...
5  Continuous research and innovation are improvi...
6  The potential of NLP is vast, making it essent...

In [5]:
results=df['Text'].apply(process_text)
results

0    {'Original_text': 'Natural Language Processing...
1    {'Original_text': 'It bridges the gap between ...
2    {'Original_text': 'NLP techniques are widely u...
3    {'Original_text': 'Machine translation and spe...
4    {'Original_text': 'Despite its advancements, N...
5    {'Original_text': 'Continuous research and inn...
6    {'Original_text': 'The potential of NLP is vas...
Name: Text, dtype: object

In [6]:
results=df['Text'].apply(process_text)
processed_df=pd.DataFrame(results.tolist())
print(processed_df.head())

                                       Original_text  ...                                  Lemmatized_tokens
0  Natural Language Processing is a fascinating f...  ...  [natural, language, processing, fascinating, f...
1  It bridges the gap between humans and machines...  ...  [bridge, gap, human, machine, enabling, comput...
2  NLP techniques are widely used in applications...  ...  [nlp, technique, widely, used, application, ch...
3  Machine translation and speech recognition are...  ...  [machine, translation, speech, recognition, co...
4  Despite its advancements, NLP faces challenges...  ...  [despite, advancement, ,, nlp, face, challenge...

[5 rows x 4 columns]

In [7]:
processed_file_path="processed_nlp_dataset.csv"
processed_df.to_csv(processed_file_path,index=False)